# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894d18d5e54fa72a59e4282d8907f1a810ee18c12ae798e95d41f12fc5e2f16b603b3550869b004f743a037f8d00647ce6f5553b195f174998520bc6df084d40

test:
  secret_key_base: 2c35113204570f0443e5e9bb955c3815beea8fa228c64b721d43c727074c403338970045533b5c2d6df24e4d847c61e824c2ab7def534aeca7ed40a1389b85d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
